Unidad2-R2/LibreriaBootstrap/config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'admin#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  resources :users
  resources :users
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get '/signin',  to: 'sessions#new'
  get '/signout', to: 'sessions#destroy'
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'sessions/new'

  get 'welcome/index'

  resources :appointments
  resources :pets
  resources :doctors

  root 'welcome#index'

end

Unidad2-R2/LibreriaBootstrap/app/models/doctor.rb
class Doctor < ActiveRecord::Base
  has_many :appointments
  has_many :pets, :through => :appointments
  
    validates_length_of :zip, :maximum => 5
	validates :name, presence: true, length: {maximum: 35}
	validates :experience, presence: true, :inclusion => 1..100

  def self.get_name(id)
    return self.find(id).name
  end
	
end

Unidad2-R2/LibreriaBootstrap/app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:create, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor Creado Correctamente.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor Actualizado Correctamente.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor Eliminado Correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:name, :address, :city, :state, :zip, :certified_by, :experience)
    end
end

Unidad2-R2/LibreriaBootstrap/app/helpers/doctors_helper.rb
module DoctorsHelper
end

Unidad2-R2/LibreriaBootstrap/app/views/doctors/_form.html.erb
<%= form_for(@doctor) do |f| %>
  <% if @doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% @doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<form role="form">
  <div class="form-group">
    <%= f.label :Nombre, :class=>"label" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :Apellido, :class=>"label" %><br>
    <%= f.text_field :address %>
  </div>
  <div class="form-group">
    <%= f.label :Puesto, :class=>"label" %><br>
    <%= f.text_field :city %>
  </div>
  <div class="form-group">
    <%= f.label :Estado, :class=>"label" %><br>
    <%= f.text_field :state %>
  </div>
  <div class="form-group">
    <%= f.label :Certificaciones, :class=>"label" %><br>
    <%= f.number_field :zip %>
  </div>
  <div class="form-group">
    <%= f.label :Nivel_Academico, :class=>"label" %><br>
    <%= f.text_field :certified_by %>
  </div>
  <div class="form-group">
    <%= f.label :Experiencia, :class=>"label" %><br>
    <%= f.number_field :experience %>
  </div>

  <div class="actions">
    <%= f.submit :Aceptar, :class => 'button radius success'%>
  </div>
  </form>
<% end %>

Unidad2-R2/LibreriaBootstrap/app/views/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form' %>

<%= link_to 'Ver', @doctor, :class => 'button radius success' %> |
<%= link_to 'Atras', doctors_path, :class => 'button radius alert' %>

Unidad2-R2/LibreriaBootstrap/app/views/doctors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listado de Bibliotecarios</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Puesto</th>
      <th>Estado</th>
      <th>Certificaciones</th>
      <th>Nivel Academico</th>
      <th>Experiencia</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td style="color: #000000;"><%= doctor.name %></td>
        <td style="color: #000000;"><%= doctor.address %></td>
        <td style="color: #000000;"><%= doctor.city %></td>
        <td style="color: #000000;"><%= doctor.state %></td>
        <td style="color: #000000;"><%= doctor.zip %></td>
        <td style="color: #000000;"><%= doctor.certified_by %></td>
        <td style="color: #000000;"><%= doctor.experience %></td>
        <td><%= link_to 'Ver', doctor, :class => 'button radius default'%></td>
        <td><%= link_to 'Editar', edit_doctor_path(doctor), :class => 'button radius success' %></td>
        <td><%= link_to 'Eliminar', doctor, method: :delete, data: { confirm: 'Estas Seguro?' }, :class => 'button radius alert' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Bibliotecario', new_doctor_path, :class => 'button radius success' %>

Unidad2-R2/LibreriaBootstrap/app/views/doctors/new.html.erb
<h1>Nuevo Bibliotecario</h1>

<%= render 'form' %>

<%= link_to 'Atras', doctors_path, :class => 'button radius alert' %>

Unidad2-R2/LibreriaBootstrap/app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @doctor.name %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @doctor.address %>
</p>

<p>
  <strong>Puesto:</strong>
  <%= @doctor.city %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @doctor.state %>
</p>

<p>
  <strong>Nivel Academico:</strong>
  <%= @doctor.zip %>
</p>

<p>
  <strong>Certificaciones:</strong>
  <%= @doctor.certified_by %>
</p>

<p>
  <strong>Experiencia:</strong>
  <%= @doctor.experience %>
</p>

<%= link_to 'Editar', edit_doctor_path(@doctor), :class => 'button radius success' %> |
<%= link_to 'Atras', doctors_path, :class => 'button radius alert' %>