Unidad2-R2/LibreriaBootstrap/config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'admin#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  resources :users
  resources :users
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get '/signin',  to: 'sessions#new'
  get '/signout', to: 'sessions#destroy'
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'sessions/new'

  get 'welcome/index'

  resources :appointments
  resources :pets
  resources :doctors

  root 'welcome#index'

end

Unidad2-R2/LibreriaBootstrap/app/models/pet.rb
class Pet < ActiveRecord::Base
  has_many :appointments
  has_many :doctors, :through => :appointments

  validates :name, presence: true, length: {maximum: 35}
  validates :breed, presence: true
  #validates :pet_type, :inclusion => { :in => %w(gato perro pajaro),
   # :message => "El valor: %{value} No es valido! La mascota tiene que ser gato, perro, pajaro." }
  validates :age, presence: true
  validates :weight, presence: true
  validates :last_appointment, presence: true
  
  def self.get_name(id)
    return self.find(id).name
  end
end

Unidad2-R2/LibreriaBootstrap/app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:create, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Animal Creado Correctamente.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Animal Actualizado Correctamente.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Animal Eliminado Correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :breed, :type, :age, :weight, :last_appointment)
    end
end

Unidad2-R2/LibreriaBootstrap/app/helpers/pets_helper.rb
module PetsHelper
end

Unidad2-R2/LibreriaBootstrap/app/views/pets/_form.html.erb
<%= form_for(@pet) do |f| %>
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>
      <ul>
      <% @pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Titulo, :class=>"label" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :Autor, :class=>"label" %><br>
    <%= f.text_field :breed %>
  </div>
  <div class="field">
    <%= f.label :Genero, :class=>"label" %><br>
    <%= f.text_field :pet_type %>
  </div>
  <div class="field">
    <%= f.label :Número_Hojas, :class=>"label" %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :Peso, :class=>"label" %><br>
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :Fecha_publicación, :class=>"label" %><br>
    <%= f.date_select :last_appointment %>

  </div>
  <div class="actions">
    <%= f.submit :Aceptar, :class => 'button radius success'%>
  </div>
<% end %>

Unidad2-R2/LibreriaBootstrap/app/views/pets/edit.html.erb
<h1>Editar Libro</h1>

<%= render 'form' %>

<%= link_to 'Ver', @pet, :class => 'button radius success' %> |
<%= link_to 'Atras', pets_path, :class => 'button radius alert' %>

Unidad2-R2/LibreriaBootstrap/app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Libros.</h1>

<table class="table">
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Autor</th>
      <th>Genero</th>
      <th>Número de Hojas</th>
      <th>Peso</th>
      <th>Fecha publicación</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td style="color:#000000"><%= pet.name %></td>
        <td style="color:#000000"><%= pet.breed %></td>
        <td style="color:#000000"><%= pet.pet_type %></td>
        <td style="color:#000000"><%= pet.age %></td>
        <td style="color:#000000"><%= pet.weight %></td>
        <td style="color:#000000"><%= pet.last_appointment %></td>
        <td><%= link_to 'Show', pet, :class => 'button radius default' %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet), :class => 'button radius success' %></td>
        <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'button radius alert' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Libro', new_pet_path, :class => 'button radius success' %>

Unidad2-R2/LibreriaBootstrap/app/views/pets/new.html.erb
<h1>Nuevo Libro</h1>

<%= render 'form' %>

<%= link_to 'Atras', pets_path, :class => 'button radius alert' %>

Unidad2-R2/LibreriaBootstrap/app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @pet.breed %>
</p>

<p>
  <strong>Genero:</strong>
  <%= @pet.pet_type %>
</p>

<p>
  <strong>Número de hojas:</strong>
  <%= @pet.age %>
</p>

<p>
  <strong>Peso:</strong>
  <%= @pet.weight %>
</p>

<p>
  <strong>Fecha publicación:</strong>
  <%= @pet.last_appointment %>
</p>

<%= link_to 'Editar', edit_pet_path(@pet), :class => 'button radius success' %> |
<%= link_to 'Atras', pets_path, :class => 'button radius alert' %>